#!/usr/bin/env python3
"""price_hour.py -- every clock hour: the top-of-hour snapshot in, a price per shelf out.

GENERATED by ops.integration; the code is src/ops/price_hour.py. Runs from this
folder whatever the caller's working directory, so a relative path in an
argument is relative to the folder.

    python3 price_hour.py --help
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)
sys.path.insert(0, os.path.join(HERE, "src"))

from ops.price_hour import main                                        # noqa: E402

if __name__ == "__main__":
    sys.exit(main())
