"""ops.integration -- the standalone pricing folder engineering runs, and
the artifact sync that keeps it current.

`integration/` is what the pricing host needs and nothing else:

    integration/
      README.md            the handoff (docs/integration_README.md, verbatim)
      price_hour.py        every clock hour: the snapshot in, a price per shelf out
      build_features.py    every morning: the day's feature table from the feed
      check_inputs.py      their three tables, and the hour's response, checked
      config.yaml          the owner's readings
      requirements.lock    the pinned libraries
      artifacts/  data/    SYNCED from the owner's chain (below); never in git
      snapshots/ feed/ failures/ features/ decisions/ reports/hours/ logs/ events_store/
      examples/  docs/     the four example tables, the handover page
      src/                 the engine: the exact import closure of the three
                           commands, copied verbatim with the package layout kept
      MANIFEST.json        every generated file with its digest

The three commands are thin wrappers: each sets the working directory to
the folder and `src/` on the path, then runs the module it names, so no
import is rewritten and a command run from anywhere still reads THIS
folder's config and artifacts. The episode id is the producers': the
rule module rides along inside src/ because the hourly job counts the
ids that disagree with it, but nothing here assigns one. The learning
lane is deliberately absent: this folder prices.

GENERATED, never edited. `build()` writes it; `tests/test_integration_bundle.py`
pins the committed folder to a fresh build byte for byte, proves the
closure is closed, and runs the commands from a copy with the
repository off the path.

`sync(cfg)` copies the artifacts the config names (the sealed bundle, the
posterior, the prior), the extract and the rolling feed history, and the
config itself into the folder. `ops.seal` calls it after every seal and
`ops.advance` at the end of every run, so a retrain, a paste round or a
posterior re-init reaches the folder without a hand step. It targets
`integration/` under the CURRENT working directory -- the repo root when
the owner runs the chain, a workspace's own folder in a rehearsal -- and
does nothing where no built folder exists.

Run: python3 -m ops.integration [--out integration] [--check | --sync]
"""

import argparse
import ast
import datetime as dt
import hashlib
import json
import os
import shutil
import sys
import tempfile

from common.config import config_get, load_config
from common.paths import RAW

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = "integration"
SRC = "src"
PACKAGES = ("common", "engine", "events", "fit", "daily", "ops")
MANIFEST = "MANIFEST.json"
SYNCED = os.path.join("artifacts", "synced.json")

# the commands, in the README's order: wrapper name -> (module, one line)
COMMANDS = (
    ("price_hour.py", "ops.price_hour",
     "every clock hour: the top-of-hour snapshot in, a price per shelf out"),
    ("build_features.py", "daily.features",
     "every morning, after yesterday's feed lands: the day's feature table"),
    ("check_inputs.py", "ops.check_inputs",
     "the snapshot, the feed, the failed pushes and the hour's response, checked"),
)
ENTRIES = tuple(mod for _, mod, _ in COMMANDS)

# copied as they are, beside the commands
FILES = ("config.yaml", "requirements.txt", "requirements.lock",
         "docs/engineering_handover.html")
DIRS = ("examples",)
README_SRC = os.path.join("docs", "integration_README.md")

# the working directories the cron lines name; created empty (git ignores
# their contents) so the first run finds them
RUNTIME_DIRS = ("snapshots", "feed", "failures", "features", "decisions",
                "reports/hours", "logs", "events_store", "artifacts", "data")

# what sync carries: the artifacts the config names, by config key
ARTIFACT_KEYS = (("artifacts", "bundle_path"),
                 ("data", "split_manifest_path"),
                 ("baseline_model", "model_path"),
                 ("baseline_model", "feature_schema_path"),
                 ("baseline_model", "calibration_factor_path"),
                 ("dispersion", "r_lookup_path"),
                 ("dispersion", "rho_path"),
                 ("posterior", "prior", "path"),
                 ("posterior", "path"))

WRAPPER = '''#!/usr/bin/env python3
"""{name} -- {line}.

GENERATED by ops.integration; the code is src/{path}. Runs from this
folder whatever the caller's working directory, so a relative path in an
argument is relative to the folder.

    python3 {name} --help
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)
sys.path.insert(0, os.path.join(HERE, "{src}"))

from {module} import main                                        # noqa: E402

if __name__ == "__main__":
    sys.exit(main())
'''


# ---------------------------------------------------------------- closure

def _module_path(root, mod):
    p = os.path.join(root, *mod.split("."))
    if os.path.isfile(p + ".py"):
        return p + ".py"
    if os.path.isfile(os.path.join(p, "__init__.py")):
        return os.path.join(p, "__init__.py")
    return None


def local_imports(root, path):
    """The repo-local modules `path` imports, module level or nested."""
    with open(path) as f:
        tree = ast.parse(f.read(), path)
    out = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name.split(".")[0] in PACKAGES:
                    out.add(a.name)
        elif isinstance(node, ast.ImportFrom) and node.module \
                and node.module.split(".")[0] in PACKAGES:
            out.add(node.module)
            for a in node.names:                 # `from pkg import module`
                if _module_path(root, f"{node.module}.{a.name}"):
                    out.add(f"{node.module}.{a.name}")
    return out


def closure(root, entries=ENTRIES):
    """Every repo-local module reachable from `entries`, sorted."""
    seen, todo = set(), list(entries)
    while todo:
        mod = todo.pop()
        if mod in seen:
            continue
        path = _module_path(root, mod)
        if path is None:
            raise SystemExit(f"cannot resolve {mod} under {root}")
        seen.add(mod)
        todo.extend(local_imports(root, path) - seen)
    return sorted(seen)


def module_files(root, mods):
    """The files that carry `mods`: each module and every package
    __init__ above it, relative to `root`."""
    files = set()
    for mod in mods:
        files.add(os.path.relpath(_module_path(root, mod), root))
        parts = mod.split(".")
        for i in range(1, len(parts)):
            init = os.path.join(*parts[:i], "__init__.py")
            if os.path.isfile(os.path.join(root, init)):
                files.add(init)
    return sorted(files)


# ------------------------------------------------------------------ build

def _digest(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _copy(src, out, rel):
    dst = os.path.join(out, rel)
    os.makedirs(os.path.dirname(dst) or out, exist_ok=True)
    shutil.copyfile(src, dst)
    return rel


def build(root=ROOT, out=None):
    """Write the folder at `out` (default <root>/integration). Returns the
    manifest. Refuses to replace a directory that is neither a previous
    build (no MANIFEST.json) nor empty; the runtime directories and what
    sync put there are kept."""
    out = out or os.path.join(root, OUT)
    if os.path.isdir(out) and os.listdir(out) \
            and not os.path.exists(os.path.join(out, MANIFEST)):
        raise SystemExit(f"{out} exists and is not a previous build -- refusing to replace it")
    keep = {d.split("/")[0] for d in RUNTIME_DIRS}
    if os.path.isdir(out):
        for name in os.listdir(out):
            if name in keep:
                continue
            p = os.path.join(out, name)
            shutil.rmtree(p) if os.path.isdir(p) else os.remove(p)
    os.makedirs(out, exist_ok=True)

    mods = closure(root)
    copied = [_copy(os.path.join(root, rel), out, os.path.join(SRC, rel))
              for rel in module_files(root, mods)]
    for name, mod, line in COMMANDS:
        with open(os.path.join(out, name), "w") as f:
            f.write(WRAPPER.format(name=name, line=line, module=mod, src=SRC,
                                   path=mod.replace(".", "/") + ".py"))
        os.chmod(os.path.join(out, name), 0o755)
        copied.append(name)
    for rel in FILES:
        copied.append(_copy(os.path.join(root, rel), out, rel))
    for d in DIRS:
        for name in sorted(os.listdir(os.path.join(root, d))):
            copied.append(_copy(os.path.join(root, d, name), out, os.path.join(d, name)))
    copied.append(_copy(os.path.join(root, README_SRC), out, "README.md"))
    for d in RUNTIME_DIRS:
        os.makedirs(os.path.join(out, d), exist_ok=True)

    manifest = {
        "what": "the standalone pricing folder; GENERATED by ops.integration, never edited",
        "commands": [name for name, _, _ in COMMANDS],
        "modules": mods,
        "files": {rel: _digest(os.path.join(out, rel)) for rel in sorted(copied)},
    }
    with open(os.path.join(out, MANIFEST), "w") as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
        f.write("\n")
    return manifest


def stale(root=ROOT, out=None):
    """The files that differ between `out` and a fresh build: [] when the
    committed folder is current."""
    out = out or os.path.join(root, OUT)
    with tempfile.TemporaryDirectory() as tmp:
        want = build(root, os.path.join(tmp, "fresh"))["files"]
    have = {}
    if os.path.exists(os.path.join(out, MANIFEST)):
        with open(os.path.join(out, MANIFEST)) as f:
            have = json.load(f).get("files") or {}

    def on_disk(rel):
        p = os.path.join(out, rel)
        return _digest(p) if os.path.exists(p) else None

    return sorted(rel for rel in set(want) | set(have)
                  if want.get(rel) is None or on_disk(rel) != want[rel])


# ------------------------------------------------------------------- sync

def sync(cfg, out=OUT, config_path="config.yaml"):
    """Copy the artifacts `cfg` names, the extract and the rolling feed
    history, and the config into the folder at `out` (relative to the
    working directory). Returns {"copied", "absent", "bundle"} or None
    where no built folder exists. An artifact not on disk yet is listed,
    never an error: the chain syncs after every seal, and the first seal
    predates the posterior."""
    if not os.path.exists(os.path.join(out, MANIFEST)):
        return None
    copied, absent = [], []
    for key in ARTIFACT_KEYS:
        src = config_get(cfg, key, default=None)
        if src and os.path.exists(src):
            copied.append(_copy(src, out, os.path.join("artifacts", os.path.basename(src))))
        else:
            absent.append(".".join(key))
    for src in (RAW, config_get(cfg, ("features", "history_path"), default=None)):
        if src and os.path.exists(src):
            copied.append(_copy(src, out, os.path.join("data", os.path.basename(src))))
    if os.path.exists(config_path):
        copied.append(_copy(config_path, out, "config.yaml"))
    bundle = None
    bp = config_get(cfg, ("artifacts", "bundle_path"), default=None)
    if bp and os.path.exists(bp):
        with open(bp) as f:
            bundle = (json.load(f) or {}).get("bundle")
    record = {"at": dt.datetime.now(dt.timezone.utc).isoformat(),
              "bundle": bundle, "copied": copied, "absent": absent,
              "sha256": {rel: _digest(os.path.join(out, rel)) for rel in copied}}
    os.makedirs(os.path.join(out, "artifacts"), exist_ok=True)
    with open(os.path.join(out, SYNCED), "w") as f:
        json.dump(record, f, indent=1)
        f.write("\n")
    return record


def sync_and_print(cfg, out=OUT, config_path="config.yaml"):
    """sync, one line on stdout; the hook ops.seal and ops.advance call."""
    rec = sync(cfg, out, config_path)
    if rec is None:
        return None
    print(f"synced {len(rec['copied'])} file(s) -> {out}/ (bundle {rec['bundle']})"
          + (f"; not on disk yet: {', '.join(rec['absent'])}" if rec["absent"] else ""))
    return rec


def main(argv=None):
    ap = argparse.ArgumentParser(prog="ops.integration")
    ap.add_argument("--out", default=None, help=f"default {OUT}/")
    ap.add_argument("--check", action="store_true",
                    help="compare the folder to a fresh build; exit 1 if it is stale")
    ap.add_argument("--sync", action="store_true",
                    help="copy the artifacts, the data and the config into the folder")
    ap.add_argument("--config", default="config.yaml")
    args = ap.parse_args(argv)
    if args.check:
        diff = stale(ROOT, args.out)
        if diff:
            print(f"{OUT}/ is STALE -- rebuild with python3 -m ops.integration:")
            for rel in diff:
                print(f"  {rel}")
            return 1
        print(f"{OUT}/ is current")
        return 0
    if args.sync:
        rec = sync_and_print(load_config(args.config), args.out or OUT, args.config)
        if rec is None:
            print(f"no built folder at {args.out or OUT}/ -- build it first")
            return 1
        return 0
    m = build(ROOT, args.out)
    print(f"{len(m['modules'])} modules, {len(m['files'])} files -> {args.out or OUT}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
