"""ops.integration -- keep the standalone pricing folder engineering runs
honest and current: the artifact sync, and the check that its copies
still match their sources.

`integration/` is the hourly price and what it needs, nothing else:

    integration/
      README.md            the handoff
      price_hour.py        every clock hour: the snapshot in, a price per shelf out
      config.yaml          GENERATED by sync: the repository's config pruned to the
                           keys an exploit-only hour reads (KEEP below)
      requirements.lock    the pinned libraries
      artifacts/           SYNCED: the five files the hour opens (ARTIFACT_KEYS)
      features/            SYNCED: the day's feature table the owner's morning
                           lane writes (features/<day>.parquet)
      snapshots/ decisions/ reports/hours/ logs/ events_store/
      examples/  docs/     the four example tables, the handover page
      src/                 the hourly path, one file per repository module
      MANIFEST.json        every file: its source, verbatim or curated (and why)

The folder is maintained IN PLACE, never generated wholesale: the owner
asked for a minimal standalone folder without refactoring the
repository, so `src/` carries the hourly command's modules copied file
by file, and the handful that differ from their source -- a re-export
dropped, the model applier split from the trainer, the loader trimmed
to the one gate, exploit-only fixed on -- are listed in MANIFEST.json as
`curated` with the reason. Every other file is `verbatim` and `check()`
refuses a copy that no longer equals its repository source, so a fix to
the engine is either ported to the folder or fails the suite. Nothing
in the folder generates an artifact or a feature table: the owner's
chain does, in the repository, and `sync` copies the result in.

`sync(cfg)` copies the five artifacts, the feature tables and the pruned
config into the folder. `ops.seal` calls it after every seal and
`ops.advance` at the end of every run (the morning `--feed` run
included, which is what carries each day's feature table), so a
retrain, a paste round, a posterior re-init or a new morning reaches
the folder without a hand step. It targets `integration/` under the
CURRENT working directory and does nothing where no folder exists.

Run: python3 -m ops.integration --check | --sync [--out integration]
"""

import argparse
import ast
import datetime as dt
import hashlib
import json
import os
import shutil
import sys

import yaml

from common.config import config_get, load_config

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = "integration"
SRC = "src"
PACKAGES = ("common", "engine", "events", "fit", "daily", "ops")
MANIFEST = "MANIFEST.json"
SYNCED = os.path.join("artifacts", "synced.json")
COMMANDS = ("price_hour.py",)
ENTRY = "ops.price_hour"

# the runtime state the cron line names; ignored by git
RUNTIME_DIRS = ("snapshots", "features", "decisions", "reports/hours", "logs",
                "events_store", "artifacts")

# the artifacts an exploit-only hour OPENS (traced, not guessed): the model,
# its schema, the level factors, the r table, the belief. Not the prior,
# the seal, the split manifest or the audit history -- the learning lane's
ARTIFACT_KEYS = (("baseline_model", "model_path"),
                 ("baseline_model", "feature_schema_path"),
                 ("baseline_model", "calibration_factor_path"),
                 ("dispersion", "r_lookup_path"),
                 ("posterior", "path"))

# the config keys an exploit-only hour READS (traced on a dry-run hour and
# read off the path's modules): everything else in config.yaml belongs to
# the training chain, the harnesses or the learning lane and is pruned.
# A whole section keeps every key under it.
KEEP = (("meta", "config_version"),
        ("data", "launch_date"),              # the switch: null refuses to price
        ("data", "max_window_hours"),         # the planning horizon's cap
        ("reference_discount",),              # the category anchors, d_ref
        ("baseline_model", "model_path"),
        ("baseline_model", "feature_schema_path"),
        ("baseline_model", "calibration_factor_path"),
        ("dispersion", "r_lookup_path"),
        ("posterior", "path"),
        ("posterior", "epsilon_max"),         # the sign constraint delta_min floors on
        ("exploration", "delta_min_log_bias"),
        ("exploration", "delta_min_bias_multiple"),
        ("exploration", "min_feasible_tiers"),
        ("pricing", "tier_step"),
        ("pricing", "entry_offsets"),
        ("pricing", "negbin_max_k"),
        ("pricing", "demand_floor"),
        ("events", "store_dir"))

CONFIG_HEADER = """\
# GENERATED by the owner's `python3 -m ops.integration --sync` from the
# repository's config.yaml: the keys an exploit-only hour reads, nothing
# else. The values are the owner's readings; do not edit them here -- the
# next sync overwrites this file. `data.launch_date` null refuses to price
# (the pre-launch state); the owner sets it on launch day.
"""


def _digest(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _copy(src, out, rel):
    dst = os.path.join(out, rel)
    os.makedirs(os.path.dirname(dst) or out, exist_ok=True)
    shutil.copyfile(src, dst)
    return rel


# ----------------------------------------------------------------- config

def prune(cfg, keep=KEEP):
    """`cfg` reduced to `keep`: a one-key path keeps its whole section; a
    path the source lacks is left out, never raised on (the hour's own
    loader is what refuses a missing key, by name)."""
    out = {}
    for path in keep:
        node = cfg
        try:
            for k in path:
                node = node[k]
        except (KeyError, TypeError):
            continue
        dst = out
        for k in path[:-1]:
            dst = dst.setdefault(k, {})
        dst[path[-1]] = node
    return out


def pruned_text(cfg):
    return CONFIG_HEADER + yaml.safe_dump(prune(cfg), sort_keys=False, allow_unicode=True)


# ---------------------------------------------------------------- closure

def _module_path(root, mod):
    p = os.path.join(root, *mod.split("."))
    if os.path.isfile(p + ".py"):
        return p + ".py"
    if os.path.isfile(os.path.join(p, "__init__.py")):
        return os.path.join(p, "__init__.py")
    return None


def local_imports(root, path):
    """The repo-local modules `path` imports, module level or nested."""
    with open(path) as f:
        tree = ast.parse(f.read(), path)
    out = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name.split(".")[0] in PACKAGES:
                    out.add(a.name)
        elif isinstance(node, ast.ImportFrom) and node.module \
                and node.module.split(".")[0] in PACKAGES:
            out.add(node.module)
            for a in node.names:                 # `from pkg import module`
                if _module_path(root, f"{node.module}.{a.name}"):
                    out.add(f"{node.module}.{a.name}")
    return out


def modules(src):
    """Every module under `src`, dotted."""
    out = []
    for dp, _, fs in os.walk(src):
        if "__pycache__" in dp:
            continue
        for f in fs:
            if f.endswith(".py"):
                rel = os.path.relpath(os.path.join(dp, f), src)[:-3]
                out.append(rel.replace(os.sep, ".").removesuffix(".__init__"))
    return sorted(out)


def closure(src, entry=ENTRY):
    """The modules `entry` reaches inside `src`."""
    seen, todo = set(), [entry]
    while todo:
        mod = todo.pop()
        if mod in seen or _module_path(src, mod) is None:
            continue
        seen.add(mod)
        todo.extend(local_imports(src, _module_path(src, mod)) - seen)
    return sorted(seen)


def unresolved(src):
    """(module, import) pairs whose import is not inside src/: [] when the
    folder is standalone."""
    out = []
    for mod in modules(src):
        for dep in local_imports(src, _module_path(src, mod)):
            if _module_path(src, dep) is None:
                out.append((mod, dep))
    return out


# ------------------------------------------------------------------ check

def check(root=ROOT, out=None):
    """The folder against its manifest and the repository. `drift`: a
    verbatim file that no longer equals its source, or the generated
    config that no longer equals a fresh prune; `missing`: a manifested
    file not on disk; `unlisted`: a file on disk the manifest does not
    carry; `dangling`: an import that leaves src/; `unreached`: a module
    under src/ the hourly command does not import. All empty means the
    folder is current, standalone and minimal."""
    out = out or os.path.join(root, OUT)
    with open(os.path.join(out, MANIFEST)) as f:
        manifest = json.load(f)
    files = manifest["files"]
    drift, missing = [], []
    for rel, entry in files.items():
        here = os.path.join(out, rel)
        if not os.path.exists(here):
            missing.append(rel)
            continue
        if entry.get("generated") == "pruned config":
            with open(os.path.join(root, "config.yaml")) as f:
                want = pruned_text(yaml.safe_load(f))
            with open(here) as f:
                if f.read() != want:
                    drift.append(rel)
        elif entry.get("verbatim"):
            src = os.path.join(root, entry["from"])
            if not os.path.exists(src) or _digest(src) != _digest(here):
                drift.append(rel)
    skip = {d.split("/")[0] for d in RUNTIME_DIRS}
    on_disk = set()
    for dp, dns, fs in os.walk(out):
        dns[:] = [d for d in dns if d != "__pycache__"
                  and not (dp == out and d in skip)]
        for f in fs:
            rel = os.path.relpath(os.path.join(dp, f), out)
            if rel != MANIFEST:
                on_disk.add(rel)
    src = os.path.join(out, SRC)
    reached = set(closure(src))
    return {"drift": sorted(drift), "missing": sorted(missing),
            "unlisted": sorted(on_disk - set(files)),
            "dangling": unresolved(src),
            "unreached": sorted(m for m in modules(src) if m not in reached
                                and _module_path(src, m).endswith("__init__.py") is False),
            "curated": {rel: e["curated"] for rel, e in files.items() if e.get("curated")}}


def current(root=ROOT, out=None):
    r = check(root, out)
    return not (r["drift"] or r["missing"] or r["unlisted"] or r["dangling"] or r["unreached"])


# ------------------------------------------------------------------- sync

def sync(cfg, out=OUT, config_path="config.yaml"):
    """Copy the five artifacts, every feature table and the pruned config
    into the folder at `out` (relative to the working directory). Returns
    {"copied", "absent", "bundle"}, or None where no folder exists or the
    config is not the owner's (no `meta.config_version`: a harness stub
    must never overwrite the folder). An artifact not on disk yet is
    listed, never an error: the chain syncs after every seal, and the
    first seal predates the posterior."""
    if not os.path.exists(os.path.join(out, MANIFEST)):
        return None
    if config_get(cfg, ("meta", "config_version"), default=None) is None:
        return None                 # not the owner's config (a harness stub): touch nothing
    copied, absent = [], []
    for key in ARTIFACT_KEYS:
        src = config_get(cfg, key, default=None)
        if src and os.path.exists(src):
            copied.append(_copy(src, out, os.path.join("artifacts", os.path.basename(src))))
        else:
            absent.append(".".join(key))
    table_dir = config_get(cfg, ("features", "table_dir"), default="features")
    if os.path.isdir(table_dir):
        for name in sorted(os.listdir(table_dir)):
            if name.endswith(".parquet"):
                copied.append(_copy(os.path.join(table_dir, name), out,
                                    os.path.join("features", name)))
    for d in RUNTIME_DIRS:
        os.makedirs(os.path.join(out, d), exist_ok=True)
    text = pruned_text(cfg)                     # built first: a failure leaves the file whole
    tmp = os.path.join(out, "config.yaml.tmp")
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, os.path.join(out, "config.yaml"))
    copied.append("config.yaml")
    bundle = None
    bp = config_get(cfg, ("artifacts", "bundle_path"), default=None)
    if bp and os.path.exists(bp):
        with open(bp) as f:
            bundle = (json.load(f) or {}).get("bundle")
    record = {"at": dt.datetime.now(dt.timezone.utc).isoformat(),
              "bundle": bundle, "copied": copied, "absent": absent,
              "sha256": {rel: _digest(os.path.join(out, rel)) for rel in copied}}
    with open(os.path.join(out, SYNCED), "w") as f:
        json.dump(record, f, indent=1)
        f.write("\n")
    return record


def sync_and_print(cfg, out=OUT, config_path="config.yaml"):
    """sync, one line on stdout; the hook ops.seal and ops.advance call."""
    rec = sync(cfg, out, config_path)
    if rec is None:
        return None
    print(f"synced {len(rec['copied'])} file(s) -> {out}/ (bundle {rec['bundle']})"
          + (f"; not on disk yet: {', '.join(rec['absent'])}" if rec["absent"] else ""))
    return rec


def main(argv=None):
    ap = argparse.ArgumentParser(prog="ops.integration")
    ap.add_argument("--out", default=None, help=f"default {OUT}/")
    ap.add_argument("--check", action="store_true",
                    help="verbatim copies against their sources, the pruned config against "
                         "a fresh prune, the manifest against the disk, every import inside "
                         "src/, every module reached by the command; exit 1 on any finding")
    ap.add_argument("--sync", action="store_true",
                    help="copy the artifacts, the feature tables and the pruned config into the folder")
    ap.add_argument("--config", default="config.yaml")
    args = ap.parse_args(argv)
    if args.check:
        r = check(ROOT, args.out)
        for what in ("drift", "missing", "unlisted", "dangling", "unreached"):
            for item in r[what]:
                print(f"  {what:<9} {item}")
        ok = not (r["drift"] or r["missing"] or r["unlisted"] or r["dangling"] or r["unreached"])
        print(f"{OUT}/ is {'current' if ok else 'NOT current'}: "
              f"{len(r['curated'])} curated file(s), the rest verbatim")
        return 0 if ok else 1
    if args.sync:
        rec = sync_and_print(load_config(args.config), args.out or OUT, args.config)
        if rec is None:
            print(f"no folder at {args.out or OUT}/")
            return 1
        return 0
    ap.error("pass --check or --sync")


if __name__ == "__main__":
    sys.exit(main())
