"""ops.integration -- keep the standalone pricing folder engineering runs
honest and current: the artifact sync, and the check that the folder is
whole, standalone and listed.

`integration/` is the hourly price, the morning table it joins on, and
what the two need, nothing else:

    integration/
      README.md            the handoff
      price_hour.py        every clock hour: the snapshot in, a price per shelf out
      build_features.py    every morning: yesterday's feed in, the day's table out
      pricing/             the code behind the two commands, THIS FOLDER'S OWN:
                           thirteen small modules written for it, not copies of
                           the repository's (the map is pricing/__init__.py)
      config.yaml          GENERATED by sync: the repository's config pruned to the
                           keys the two commands read (KEEP below)
      requirements.lock    the pinned libraries
      artifacts/           SYNCED: the five files the hour opens (ARTIFACT_KEYS)
      data/                SYNCED: the extract the first morning seeds from; then
                           the rolling feed history the builder keeps
      snapshots/ feed/ features/ decisions/ reports/hours/ logs/ events_store/
      examples/  docs/     the four example tables, the handover page (verbatim copies)
      MANIFEST.json        every file: own, a verbatim copy (of what), or generated

The folder is maintained IN PLACE and the repository is not refactored
for it (the owner's call). Its code is a from-scratch rewrite of the
hourly path and the morning table, exploit only and STATELESS: a row is
priced from itself, the artifacts and the feature table of its episode's
opening day -- the row's `episode_id` is the opening tag, so an entry is
the row whose tag is its own shelf-hour; a later hour is anchored on the
price in force the row carries (the price applied last hour, piped back
by the producers); nothing is looked up from an earlier hour and the log
it appends to is never read there. It decides as the repository's
stateful `ops.price_hour` does: the suite prices an entry hour and the
next hour through both and refuses a difference in any field of the
decision event or the rejection record (test_end_to_end).
So an engine fix in the repository is PORTED to `pricing/` by hand, and
the parity test is what says the port is complete. `check()` keeps the
rest honest: a verbatim copy (the handover page, the examples, the
requirements) that no longer equals its source, the generated config
behind a fresh prune, a file on disk the manifest does not list or a
listed file gone, an import that leaves the package, a module the two
commands never import. Nothing in the folder fits, seals or checks: the
owner's chain does, in the repository.

`sync(cfg)` copies the five artifacts, the extract the first morning
seeds from, the rolling feed history where one exists, and the pruned
config into the folder. `ops.seal` calls it after every seal and
`ops.advance` at the end of every run, so a retrain, a paste round or a
posterior re-init reaches the folder without a hand step. It targets
`integration/` under the CURRENT working directory and does nothing where
no folder exists.

Run: python3 -m ops.integration --check | --sync [--out integration]
"""

import argparse
import ast
import datetime as dt
import hashlib
import json
import os
import shutil
import sys

import yaml

from common.config import config_get, load_config
from common.paths import RAW

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = "integration"
CODE = "pricing"                          # the package, at the folder's root
PACKAGES = (CODE,)
MANIFEST = "MANIFEST.json"
SYNCED = os.path.join("artifacts", "synced.json")
COMMANDS = ("price_hour.py", "build_features.py")
ENTRIES = ("pricing.hour", "pricing.features")     # what the two commands import

# the runtime state the cron line names; ignored by git
RUNTIME_DIRS = ("snapshots", "feed", "features", "decisions", "reports/hours", "logs",
                "events_store", "artifacts", "data")

# the artifacts an exploit-only hour OPENS (traced, not guessed): the model,
# its schema, the level factors, the r table, the belief. Not the prior,
# the seal, the split manifest or the audit history -- the learning lane's
ARTIFACT_KEYS = (("baseline_model", "model_path"),
                 ("baseline_model", "feature_schema_path"),
                 ("baseline_model", "calibration_factor_path"),
                 ("dispersion", "r_lookup_path"),
                 ("posterior", "path"))

# the config keys the two commands READ (every cfg[...] in pricing/):
# everything else in config.yaml belongs to the training chain, the
# harnesses or the learning lane and is pruned. A whole section keeps
# every key under it.
KEEP = (("meta", "config_version"),          # recorded on every decision event
        ("data", "launch_date"),              # the switch: null refuses to price
        ("data", "max_window_hours"),         # the planning horizon's cap
        ("reference_discount",),              # the category anchors, d_ref
        ("baseline_model", "ref_rate_window_days"),   # the two demand-rate features
        ("baseline_model", "ref_rate_anchor_band"),
        ("features", "table_dir"),            # the morning table: where, from what, how far back
        ("features", "history_path"),
        ("features", "history_days"),
        ("baseline_model", "model_path"),
        ("baseline_model", "feature_schema_path"),
        ("baseline_model", "calibration_factor_path"),
        ("dispersion", "r_lookup_path"),
        ("posterior", "path"),
        ("pricing", "tier_step"),
        ("pricing", "entry_offsets"),
        ("pricing", "negbin_max_k"),
        ("pricing", "demand_floor"),
        ("events", "store_dir"))
# NOT kept, on purpose: the exploration section and posterior.epsilon_max
# (they set delta_min, the floor under a draw that never happens here --
# the event records 0, "no floor"); data.exclusion_window (a training-time
# exclusion of a past period the folder's 45-day rolling history never
# reaches); data.manufacturing_window_hours and exploration
# .min_feasible_tiers (read by nothing in the folder).

CONFIG_HEADER = """\
# GENERATED by the owner's `python3 -m ops.integration --sync` from the
# repository's config.yaml: the keys an exploit-only hour reads, nothing
# else. The values are the owner's readings; do not edit them here -- the
# next sync overwrites this file. `data.launch_date` null refuses to price
# (the pre-launch state); the owner sets it on launch day.
"""


def _digest(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _copy(src, out, rel):
    dst = os.path.join(out, rel)
    os.makedirs(os.path.dirname(dst) or out, exist_ok=True)
    shutil.copyfile(src, dst)
    return rel


# ----------------------------------------------------------------- config

def prune(cfg, keep=KEEP):
    """`cfg` reduced to `keep`: a one-key path keeps its whole section; a
    path the source lacks is left out, never raised on (the hour's own
    loader is what refuses a missing key, by name)."""
    out = {}
    for path in keep:
        node = cfg
        try:
            for k in path:
                node = node[k]
        except (KeyError, TypeError):
            continue
        dst = out
        for k in path[:-1]:
            dst = dst.setdefault(k, {})
        dst[path[-1]] = node
    return out


def pruned_text(cfg):
    return CONFIG_HEADER + yaml.safe_dump(prune(cfg), sort_keys=False, allow_unicode=True)


# ---------------------------------------------------------------- closure

def _module_path(root, mod):
    p = os.path.join(root, *mod.split("."))
    if os.path.isfile(p + ".py"):
        return p + ".py"
    if os.path.isfile(os.path.join(p, "__init__.py")):
        return os.path.join(p, "__init__.py")
    return None


def local_imports(root, path):
    """The repo-local modules `path` imports, module level or nested."""
    with open(path) as f:
        tree = ast.parse(f.read(), path)
    out = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name.split(".")[0] in PACKAGES:
                    out.add(a.name)
        elif isinstance(node, ast.ImportFrom) and node.module \
                and node.module.split(".")[0] in PACKAGES:
            out.add(node.module)
            for a in node.names:                 # `from pkg import module`
                if _module_path(root, f"{node.module}.{a.name}"):
                    out.add(f"{node.module}.{a.name}")
    return out


def modules(out):
    """Every module of the package under the folder `out`, dotted."""
    src = os.path.join(out, CODE)
    found = []
    for dp, _, fs in os.walk(src):
        if "__pycache__" in dp:
            continue
        for f in fs:
            if f.endswith(".py"):
                rel = os.path.relpath(os.path.join(dp, f), out)[:-3]
                found.append(rel.replace(os.sep, ".").removesuffix(".__init__"))
    return sorted(found)


def closure(out, entries=ENTRIES):
    """The modules `entries` reach inside the folder."""
    seen, todo = set(), list(entries)
    while todo:
        mod = todo.pop()
        if mod in seen or _module_path(out, mod) is None:
            continue
        seen.add(mod)
        todo.extend(local_imports(out, _module_path(out, mod)) - seen)
    return sorted(seen)


def unresolved(out):
    """(module, import) pairs whose import is not inside the folder's
    package: [] when the folder is standalone."""
    found = []
    for mod in modules(out):
        for dep in local_imports(out, _module_path(out, mod)):
            if _module_path(out, dep) is None:
                found.append((mod, dep))
    return found


# ------------------------------------------------------------------ check

def check(root=ROOT, out=None):
    """The folder against its manifest and the repository. `drift`: a
    verbatim copy that no longer equals its source, or the generated
    config that no longer equals a fresh prune; `missing`: a manifested
    file not on disk; `unlisted`: a file on disk the manifest does not
    carry; `dangling`: an import that leaves the package; `unreached`: a
    module of the package neither command imports; `own`: the files the
    manifest marks as this folder's own code. Every list empty means the
    folder is current, standalone and minimal."""
    out = out or os.path.join(root, OUT)
    with open(os.path.join(out, MANIFEST)) as f:
        manifest = json.load(f)
    files = manifest["files"]
    drift, missing = [], []
    for rel, entry in files.items():
        here = os.path.join(out, rel)
        if not os.path.exists(here):
            missing.append(rel)
            continue
        if entry.get("generated") == "pruned config":
            with open(os.path.join(root, "config.yaml")) as f:
                want = pruned_text(yaml.safe_load(f))
            with open(here) as f:
                if f.read() != want:
                    drift.append(rel)
        elif entry.get("verbatim"):
            src = os.path.join(root, entry["from"])
            if not os.path.exists(src) or _digest(src) != _digest(here):
                drift.append(rel)
    skip = {d.split("/")[0] for d in RUNTIME_DIRS}
    on_disk = set()
    for dp, dns, fs in os.walk(out):
        dns[:] = [d for d in dns if d != "__pycache__"
                  and not (dp == out and d in skip)]
        for f in fs:
            rel = os.path.relpath(os.path.join(dp, f), out)
            if rel != MANIFEST:
                on_disk.add(rel)
    reached = set(closure(out))
    return {"drift": sorted(drift), "missing": sorted(missing),
            "unlisted": sorted(on_disk - set(files)),
            "dangling": unresolved(out),
            "unreached": sorted(m for m in modules(out) if m not in reached
                                and not _module_path(out, m).endswith("__init__.py")),
            "own": sorted(rel for rel, e in files.items() if e.get("own"))}


def current(root=ROOT, out=None):
    r = check(root, out)
    return not (r["drift"] or r["missing"] or r["unlisted"] or r["dangling"] or r["unreached"])


# ------------------------------------------------------------------- sync

def sync(cfg, out=OUT, config_path="config.yaml"):
    """Copy the five artifacts, every feature table and the pruned config
    into the folder at `out` (relative to the working directory). Returns
    {"copied", "absent", "bundle"}, or None where no folder exists or the
    config is not the owner's (no `meta.config_version`: a harness stub
    must never overwrite the folder). An artifact not on disk yet is
    listed, never an error: the chain syncs after every seal, and the
    first seal predates the posterior."""
    if not os.path.exists(os.path.join(out, MANIFEST)):
        return None
    if config_get(cfg, ("meta", "config_version"), default=None) is None:
        return None                 # not the owner's config (a harness stub): touch nothing
    copied, absent = [], []
    for key in ARTIFACT_KEYS:
        src = config_get(cfg, key, default=None)
        if src and os.path.exists(src):
            copied.append(_copy(src, out, os.path.join("artifacts", os.path.basename(src))))
        else:
            absent.append(".".join(key))
    # the morning builder's seed: the extract (the first morning) and the
    # rolling feed history where one exists already
    for src in (RAW, config_get(cfg, ("features", "history_path"), default=None)):
        if src and os.path.exists(src):
            copied.append(_copy(src, out, os.path.join("data", os.path.basename(src))))
    for d in RUNTIME_DIRS:
        os.makedirs(os.path.join(out, d), exist_ok=True)
    text = pruned_text(cfg)                     # built first: a failure leaves the file whole
    tmp = os.path.join(out, "config.yaml.tmp")
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, os.path.join(out, "config.yaml"))
    copied.append("config.yaml")
    bundle = None
    bp = config_get(cfg, ("artifacts", "bundle_path"), default=None)
    if bp and os.path.exists(bp):
        with open(bp) as f:
            bundle = (json.load(f) or {}).get("bundle")
    record = {"at": dt.datetime.now(dt.timezone.utc).isoformat(),
              "bundle": bundle, "copied": copied, "absent": absent,
              "sha256": {rel: _digest(os.path.join(out, rel)) for rel in copied}}
    with open(os.path.join(out, SYNCED), "w") as f:
        json.dump(record, f, indent=1)
        f.write("\n")
    return record


def sync_and_print(cfg, out=OUT, config_path="config.yaml"):
    """sync, one line on stdout; the hook ops.seal and ops.advance call."""
    rec = sync(cfg, out, config_path)
    if rec is None:
        return None
    print(f"synced {len(rec['copied'])} file(s) -> {out}/ (bundle {rec['bundle']})"
          + (f"; not on disk yet: {', '.join(rec['absent'])}" if rec["absent"] else ""))
    return rec


def main(argv=None):
    ap = argparse.ArgumentParser(prog="ops.integration")
    ap.add_argument("--out", default=None, help=f"default {OUT}/")
    ap.add_argument("--check", action="store_true",
                    help="verbatim copies against their sources, the pruned config against "
                         "a fresh prune, the manifest against the disk, every import inside "
                         "the package, every module reached by a command; exit 1 on any finding")
    ap.add_argument("--sync", action="store_true",
                    help="copy the artifacts, the feature tables and the pruned config into the folder")
    ap.add_argument("--config", default="config.yaml")
    args = ap.parse_args(argv)
    if args.check:
        r = check(ROOT, args.out)
        for what in ("drift", "missing", "unlisted", "dangling", "unreached"):
            for item in r[what]:
                print(f"  {what:<9} {item}")
        ok = not (r["drift"] or r["missing"] or r["unlisted"] or r["dangling"] or r["unreached"])
        print(f"{OUT}/ is {'current' if ok else 'NOT current'}: "
              f"{len(r['own'])} own file(s), the rest verbatim copies or generated")
        return 0 if ok else 1
    if args.sync:
        rec = sync_and_print(load_config(args.config), args.out or OUT, args.config)
        if rec is None:
            print(f"no folder at {args.out or OUT}/")
            return 1
        return 0
    ap.error("pass --check or --sync")


if __name__ == "__main__":
    sys.exit(main())
